/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_dynamsoft_JNIBarcode */

#ifndef _Included_com_dynamsoft_JNIBarcode
#define _Included_com_dynamsoft_JNIBarcode
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_dynamsoft_JNIBarcode
 * Method:    decodefile
 * Signature: ()V
 */
JNIEXPORT jint JNICALL Java_com_dynamsoft_JNIBarcode_decodefile
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
